import { Geist, Geist_Mono } from "next/font/google";
import "../styles/css/theme-1.css";
// import "../styles/css/theme-2.css";
import "../styles/css/theme-3.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import ScrollToTop from "@/components/common/ScrollToTop";
import ScriptLoader from "@/components/common/ScriptLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <ScrollToTop />

        {/* Load your theme scripts */}
        <ScriptLoader />

      </body>
    </html>
  );
}
